logo: 糖糖的网站欢迎您!  ━(*｀∀´*)ノ # add logo name
title: 糖糖的个人网站
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hereTJZ.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: "hereTJZ.github.io"

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: GLAD TO MEET YOU! # add banner title
banner-desc: 心里的火永远不要灭，哪怕别人只看得到烟~<br>心里的光永远不要暗，因为你不知道有谁会借此走出黑暗~ # add banner description

# Author settings
author-pic: face.jpg # your photo
author-name: 唐建祯 # your name
about-author: 路人皆知的工大小库里，yyds！！！ # about author
email: 952158354@qq.com # your email
qq: 952158354 # your qq
phone: 13145659923 # your pnone number
website: https://hereTJZ.github.io/ # you website

# Social link
google_url:    https://hereTJZ.github.io/ # add url link
twitter_url:   https://hereTJZ.github.io/ # add url link
instagram_url: https://hereTJZ.github.io/ # add url link
pinterest_url: https://hereTJZ.github.io/ # add url link
dribbble_url:  https://hereTJZ.github.io/ # add url link
facebook_url:  https://hereTJZ.github.io/ # add url link

# Disqus
discus_identifier: mr-brown # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

plugins: [jekyll-paginate]

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
